// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZFE5QABhFCgOkDLmyJB-0cJ3o9nahMg',
    appId: '1:752220353251:web:bc4d285959f8273cbd4bd6',
    messagingSenderId: '752220353251',
    projectId: 'diabetes-tracker-82281',
    authDomain: 'diabetes-tracker-82281.firebaseapp.com',
    storageBucket: 'diabetes-tracker-82281.appspot.com',
    measurementId: 'G-0T7EX34FRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdx0Ybdt_j7ad0EjtKpVns2tE52qiZVv8',
    appId: '1:752220353251:android:43e4e82684bffc19bd4bd6',
    messagingSenderId: '752220353251',
    projectId: 'diabetes-tracker-82281',
    storageBucket: 'diabetes-tracker-82281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaiLEH7D8E0kTknKnV7XVWDIN12X_DABQ',
    appId: '1:752220353251:ios:5e0e3b04b3ae1c08bd4bd6',
    messagingSenderId: '752220353251',
    projectId: 'diabetes-tracker-82281',
    storageBucket: 'diabetes-tracker-82281.appspot.com',
    iosBundleId: 'com.example.diabetesTracker',
  );
}
